=== voelkman/Judicator/Judicator/src/java/de/voelkman/config/dtd/profession.dtd
<!ELEMENT professions (skillconfig, profession+)>
<!ELEMENT profession (name,
							skills,
							freeskillpoints,
							freelanguagepoints,
							languages,
							restrictions?,
							numberOfWeapons,
							incrementOFDF,
							lifepowergain,
							spellpower?,
							spellpowergain?,
							magicValues?,
							spells?,
							agebonusgain?,
							specials?
							)>


<!ELEMENT lifepowergain (type, multiplier, bonus)>
<!ELEMENT spellpowergain (type, multiplier, bonus)>
<!ELEMENT agebonusgain (#PCDATA)>
<!ELEMENT languages (language*)>
<!ELEMENT language (name,value)>
<!ELEMENT spellpower (type, multiplier, bonus)>
<!ATTLIST spellpower
		additionalPower (yes|no) "no"
>
<!ELEMENT magicValues (ability+)>
<!ELEMENT skills (ability+)>
<!ELEMENT restrictions (restriction*)>
<!ELEMENT restriction (type,type2,value)>
<!ELEMENT skillconfig (skill*)>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
		number CDATA #REQUIRED
		type (Calc|Base|Level|Percent|CalcFixed) #REQUIRED
		p1 (ST|EN|DX|AG|RE|SE|SP|PR) #IMPLIED
		p2 (ST|EN|DX|AG|RE|SE|SP|PR) #IMPLIED
		p3 (ST|EN|DX|AG|RE|SE|SP|PR) #IMPLIED
		p4 (ST|EN|DX|AG|RE|SE|SP|PR) #IMPLIED
		family CDATA #REQUIRED
>

<!ELEMENT ability (#PCDATA)>
<!ATTLIST ability
		number CDATA #REQUIRED
>

<!ELEMENT numberOfWeapons (#PCDATA)>
<!ATTLIST numberOfWeapons
		special (NO|BARBARIAN|WARRIOR|DRUID|MAGE) #REQUIRED
>
<!ATTLIST magicValues
		increment (NO|PRIMARY|SECONDARY) #REQUIRED
>
<!ELEMENT incrementOFDF (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT power (#PCDATA)>
<!ELEMENT type2 (#PCDATA)>
<!ELEMENT multiplier (#PCDATA)>
<!ELEMENT bonus (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT special (#PCDATA)>
<!ELEMENT freelanguagepoints (#PCDATA)>
<!ELEMENT freeskillpoints (#PCDATA)>
<!ELEMENT spells (spell+)>
<!ELEMENT spell (name, type, power)>
<!ELEMENT specials (special+)>

=== voelkman/Judicator/Judicator/src/java/de/voelkman/config/professions.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE professions SYSTEM "dtd/profession.dtd">
<professions>
	<skillconfig>
		<skill number="0" type="Calc" p1="SP" p2="SP" p3="RE" p4="SE" family="A">Abrichten</skill>
		<skill number="1" type="Calc" p1="AG" p2="AG" p3="AG" p4="DX" family="L">Akrobatik</skill>
		<skill number="2" type="Base" family="C">Alchemie</skill> <!--skill number="3" type="Percent">Berserkergang</skill-->
		<skill number="4" type="Calc" p1="AG" p2="AG" p3="SE" p4="SE" family="A">Beschatten</skill>
		<skill number="5" type="Calc" p1="PR" p2="PR" p3="PR" p4="SP" family="A">Betören</skill> <!--skill number="6" type="Percent">Blutrausch</skill-->
		<skill number="7" type="Calc" p1="DX" p2="AG" p3="RE" p4="SE" family="M">Fahrzeuge lenken</skill>
		<skill number="8" type="Calc" p1="DX" p2="DX" p3="DX" p4="AG" family="N">Fallen entschärfen</skill>
		<skill number="9" type="Calc" p1="DX" p2="AG" p3="RE" p4="SE"  family="N">Fallen stellen</skill>
		<skill number="10" type="Calc" p1="AG" p2="DX" p3="ST" p4="EN"  family="K">Fernkampf</skill>
		<skill number="11" type="Calc" p1="DX" p2="DX" p3="DX" p4="AG" family="N">Fesseln + Entfesseln</skill>
		<skill number="12" type="Calc" p1="AG" p2="DX" p3="ST" p4="ST" family="M">Fischen</skill>
		<skill number="13" type="Base" family="C">Gifte + Tränke</skill>
		<skill number="14" type="Calc" p1="AG" p2="AG" p3="RE" p4="SE" family="A">Hinterhalt legen</skill>
		<skill number="15" type="Calc" p1="DX" p2="DX" p3="RE" p4="RE" family="M">Kartographie</skill>
		<skill number="16" type="Calc" p1="AG" p2="DX" p3="ST" p4="EN" family="L">Klettern</skill>
		<skill number="17" type="Calc" p1="DX" p2="DX" p3="RE" p4="RE" family="N">Knoten binden</skill>
		<skill number="18" type="Base" family="M">Kochen</skill>
		<skill number="19" type="Base" family="M">Krankheit behandeln</skill>
		<skill number="20" type="Percent" family="C">Lesen + Schreiben</skill>
		<skill number="21" type="Base" family="B">Magie erspüren</skill> <!--skill number="22" type="Percent">Meditation</skill-->
		<skill number="23" type="Calc" p1="PR" p2="SP" p3="RE" p4="RE" family="B">Menschenkenntnis</skill>
		<skill number="24" type="Calc" p1="AG" p2="DX" p3="SE" p4="SE" family="N">Meucheln</skill>
		<skill number="25" type="Calc" p1="RE" p2="RE" p3="RE" p4="RE" family="B">Orientierung, Natur</skill>
		<skill number="26" type="Calc" p1="RE" p2="RE" p3="RE" p4="RE" family="B">Orientierung, Stadt</skill>
		<skill number="27" type="Base" family="C">Pflanzenkunde</skill>
		<skill number="28" type="Calc" p1="AG" p2="DX" p3="ST" p4="EN" family="L">Reiten</skill>
		<skill number="29" type="Calc" p1="RE" p2="SE" p3="PR" p4="SP" family="A">Rhetorik</skill>
		<skill number="30" type="Base"  family="C">Sagenkunde</skill>
		<skill number="31" type="Calc" p1="SP" p2="SP" p3="EN" p4="EN"  family="L">Saufen</skill>
		<skill number="32" type="Calc" p1="PR" p2="SP" p3="RE" p4="RE"  family="B">Schätzen</skill>
		<skill number="33" type="Calc" p1="AG" p2="DX" p3="ST" p4="EN" family="M">Schiffahrt</skill>
		<skill number="34" type="Calc" p1="AG" p2="AG" p3="AG" p4="DX" family="A">Schleichen</skill>
		<skill number="35" type="Calc" p1="SE" p2="RE" p3="DX" p4="DX" family="N">Schlösser öffnen</skill>
		<skill number="36" type="Calc" p1="RE" p2="RE" p3="RE" p4="RE" family="B">Sinnesschärfe</skill>
		<skill number="37" type="Percent" family="L">Schwimmen</skill>
		<skill number="38" type="Level" family="B">Sechster Sinn</skill>
		<skill number="39" type="Calc" p1="AG" p2="AG" p3="SE" p4="SE" family="A">Sich verbergen</skill>
		<skill number="40" type="Calc" p1="DX" p2="DX" p3="SP" p4="PR" family="N">Singen + Musizieren</skill>
		<skill number="41" type="Base" family="B">Spuren lesen</skill>
		<skill number="42" type="Calc" p1="SE" p2="SE" p3="SE" p4="SE" family="A">Stiefellecken</skill>
		<skill number="43" type="Calc" p1="AG" p2="DX" p3="EN" p4="EN" family="N">Tanzen</skill>
		<skill number="44" type="Calc" p1="DX" p2="DX" p3="DX" p4="AG" family="N">Taschendiebstahl</skill>
		<skill number="45" type="Calc" p1="DX" p2="DX" p3="DX" p4="DX" family="N">Taschentricks</skill>
		<skill number="46" type="Base" family="C">Tierkunde</skill>
		<skill number="47" type="Calc" p1="RE" p2="RE" p3="PR" p4="SP" family="B">Verborgenes finden</skill>
		<skill number="48" type="Calc" p1="RE" p2="SE" p3="PR" p4="SP" family="N">Verkleiden</skill>
		<skill number="49" type="CalcFixed" p1="AG" p2="AG" family="K">Waffenkampf, Reittier</skill>
		<skill number="50" type="Calc" p1="AG" p2="DX" p3="ST" p4="EN" family="K">Waffenloser Kampf</skill>
		<skill number="51" type="Calc" p1="RE" p2="RE" p3="DX" p4="DX"  family="M">Waffenreparatur</skill>
		<skill number="52" type="Calc" p1="RE" p2="RE" p3="PR" p4="SP" family="C">Wetterkunde</skill>
		<skill number="53" type="Base" family="M">Wunden behandeln</skill>
		<skill number="54" type="Calc" p1="EN" p2="EN" p3="SP" p4="SP" family="A">Zeugung v. Nachk.</skill>
		<skill number="55" type="Calc" p1="RE" p2="SE" p3="SP" p4="PR"  family="A">Information sammeln</skill>
		<skill number="56" type="Calc" p1="RE" p2="RE" p3="RE" p4="RE" family="B">Orientierung, See</skill>

	</skillconfig>
	<profession>
		<name>Krieger</name>
		<skills>
			<ability number="0">4</ability> <!-- Abrichten-->
			<ability number="1">4</ability> <!-- Akrobatik-->
			<ability number="2">0</ability> <!-- Alchemie-->
			<ability number="3">-1</ability> <!-- Berserkergang-->
			<ability number="4">3</ability> <!-- Beschatten-->
			<ability number="5">3</ability> <!-- Betören-->
			<ability number="6">-1</ability> <!-- Blutrausch-->
			<ability number="7">0</ability> <!-- Fahrzeuge lenken-->
			<ability number="8">6</ability> <!-- Fallen entschärfen-->
			<ability number="9">3</ability> <!-- Fallen stellen-->
			<ability number="10">0</ability> <!-- Fernkampf-->
			<ability number="11">4</ability> <!-- Fesseln-->
			<ability number="12">4</ability> <!-- Fischen-->
			<ability number="13">0</ability> <!-- Gifte-->
			<ability number="14">2</ability> <!-- Hinterhalt-->
			<ability number="15">5</ability> <!-- Kartographie-->
			<ability number="16">2</ability> <!-- Klettern-->
			<ability number="17">3</ability> <!-- Knoten-->
			<ability number="18">4</ability> <!-- Kochen-->
			<ability number="19">1</ability> <!-- Krankheiten-->
			<ability number="20">35</ability> <!-- Lesen-->
			<ability number="21">-1</ability> <!-- Magie-->
			<ability number="22">-1</ability> <!-- Meditation-->
			<ability number="23">4</ability> <!-- Menschenkenntnis-->
			<ability number="24">3</ability> <!-- Meucheln-->
			<ability number="25">3</ability> <!-- Orientierungssinn, Natur-->
			<ability number="26">3</ability> <!-- Orientierungssinn, Stadt-->
			<ability number="27">1</ability> <!-- Pflanzenkunde-->
			<ability number="28">0</ability> <!-- Reiten-->
			<ability number="29">4</ability> <!-- Rhetorik-->
			<ability number="30">1</ability> <!-- Sagenkunde-->
			<ability number="31">1</ability> <!-- Saufen-->
			<ability number="32">4</ability> <!-- Schätzen-->
			<ability number="33">3</ability> <!-- Schiffahrt-->
			<ability number="34">3</ability> <!-- Schleichen-->
			<ability number="35">4</ability> <!-- Schlösser-->
			<ability number="36">3</ability> <!-- Sinnesschärfe-->
			<ability number="37">50</ability> <!-- Schwimmen-->
			<ability number="38">0</ability> <!-- Sechster-->
			<ability number="39">3</ability> <!-- Sich verbergen-->
			<ability number="40">5</ability> <!-- Singen-->
			<ability number="41">5</ability> <!-- Spuren-->
			<ability number="42">5</ability> <!-- Stiefellecken-->
			<ability number="43">4</ability> <!-- Tanzen-->
			<ability number="44">5</ability> <!-- Taschendiebstahl-->
			<ability number="45">6</ability> <!-- Taschentricks-->
			<ability number="46">2</ability> <!-- Tierkunde-->
			<ability number="47">3</ability> <!-- Verborgenes-->
			<ability number="48">4</ability> <!-- Verkleiden-->
			<ability number="49">0</ability> <!-- Waffenkampf-->
			<ability number="50">0</ability> <!-- Waffenloser-->
			<ability number="51">1</ability> <!-- Waffenreparatur-->
			<ability number="52">5</ability> <!-- Wetterkunde-->
			<ability number="53">3</ability> <!-- Wunden-->
			<ability number="54">0</ability> <!-- Zeugung-->
			<ability number="55">4</ability> <!-- Informationen-->
			<ability number="56">8</ability> <!-- Orientierung See-->
			<ability number="57">0</ability><!--Gartenkunst-->
		</skills>
		<freeskillpoints>0</freeskillpoints>
		<freelanguagepoints>3</freelanguagepoints>
		<languages>
			<language>
				<name>Galdan</name>
				<value>3</value>
			</language>
		</languages>
		<numberOfWeapons special="WARRIOR">5</numberOfWeapons>
		<incrementOFDF>1</incrementOFDF>
		<lifepowergain>
			<type>10</type>
			<multiplier>1</multiplier>
			<bonus>0</bonus>
		</lifepowergain>
		<agebonusgain>2</agebonusgain>
	</profession>
	<profession>
		<name>Barbar</name>
		<skills>
			<ability number="0">3</ability>
			<ability number="1">6</ability>
			<ability number="2">0</ability>
			<ability number="3">100</ability>
			<ability number="4">5</ability>
			<ability number="5">4</ability>
			<ability number="6">-1</ability>
			<ability number="7">2</ability>
			<ability number="8">7</ability>
			<ability number="9">1</ability>
			<ability number="10">3</ability>
			<ability number="11">5</ability>
			<ability number="12">0</ability>
			<ability number="13">0</ability>
			<ability number="14">4</ability>
			<ability number="15">7</ability>
			<ability number="16">1</ability>
			<ability number="17">4</ability>
			<ability number="18">4</ability>
			<ability number="19">3</ability>
			<ability number="20">0</ability>
			<ability number="21">-1</ability>
			<ability number="22">-1</ability>
			<ability number="23">3</ability>
			<ability number="24">6</ability>
