=== voelkman/Judicator/Judicator/src/java/de/voelkman/config/dtd/races.dtd
<!ELEMENT races (race+)>

<!ELEMENT race (name,namegenerator,
						energy,
						skill,
						intelligence,
						charisma,
						lifebonus,
						spellpower?,
						spellbonus?,
						spells?,
						special*,
						age,
						height,
						weight,
						freelanguagepoints,
						languages,
						restrictions?)>

<!ELEMENT spells (spell+)>
<!ELEMENT spell (name, type, power)>
<!ELEMENT spellpower (type, multiplier, bonus)>

<!ELEMENT restrictions (restriction*)>
<!ELEMENT restriction (type,type2,value)>
<!ELEMENT age (type, multiplier, bonus)>
<!ELEMENT height (type, multiplier, bonus)>
<!ELEMENT weight (type, multiplier, bonus)>
<!ELEMENT languages (language*)>

<!ELEMENT lifebonus (#PCDATA)>
<!ELEMENT spellbonus (#PCDATA)>
<!ELEMENT language (name,value)>


<!ELEMENT energy (#PCDATA)>
<!ELEMENT skill (#PCDATA)>
<!ELEMENT intelligence (#PCDATA)>
<!ELEMENT charisma (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT multiplier (#PCDATA)>
<!ELEMENT bonus (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT power (#PCDATA)>
<!ELEMENT special (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT namegenerator (#PCDATA)>

<!ELEMENT type2 (#PCDATA)>

<!ELEMENT freelanguagepoints (#PCDATA)>

=== voelkman/Judicator/Judicator/src/java/de/voelkman/config/races.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE races SYSTEM "dtd/races.dtd" >
<races>
	<race>
        <name>Mensch</name>
        <namegenerator>German</namegenerator>
        <energy>7</energy>
        <skill>7</skill>
        <intelligence>7</intelligence>
        <charisma>8</charisma>
        <lifebonus>15</lifebonus>
        <age>
            <type>6</type>
            <multiplier>1</multiplier>
            <bonus>16</bonus>
        </age>
        <height>
            <type>10</type>
            <multiplier>5</multiplier>
            <bonus>160</bonus>
        </height>
        <weight>
            <type>10</type>
            <multiplier>3</multiplier>
            <bonus>65</bonus>
        </weight>
        <freelanguagepoints>9</freelanguagepoints>
        <languages/>
    </race>
    <race>
        <name>Elf</name>
        <namegenerator>Elves</namegenerator>
        <energy>5</energy>
        <skill>8</skill>
        <intelligence>7</intelligence>
        <charisma>9</charisma>
        <lifebonus>10</lifebonus>
        <spellpower>
            <type>6</type>
            <multiplier>2</multiplier>
            <bonus>0</bonus>
        </spellpower>
        <spellbonus>2</spellbonus>
        <spells>
            <spell>
                <name>Elfenhauch*</name>
                <type>NAT</type>
                <power>2 ZAK/LK*</power>
            </spell>
            <spell>
                <name>Graumantel</name>
                <type>NAT</type>
                <power>3 ZAK</power>
            </spell>
            <spell>
                <name>Wahres sehen</name>
                <type>NAT</type>
                <power>5 ZAK</power>
            </spell>
        </spells>
        <special>Nachtsicht</special>
        <special>Keine Magier-Spezialisierung ab 10.Rang</special>
        <age>
            <type>50</type>
            <multiplier>6</multiplier>
            <bonus>50</bonus>
        </age>
        <height>
            <type>20</type>
            <multiplier>1</multiplier>
            <bonus>160</bonus>
        </height>
        <weight>
            <type>20</type>
            <multiplier>1</multiplier>
            <bonus>40</bonus>
        </weight>
        <freelanguagepoints>6</freelanguagepoints>
        <languages>
            <language>
                <name>Alayani</name>
                <value>6</value>
            </language>
        </languages>
        <restrictions>
            <restriction>
                <type>Sp</type>
                <type2>Pr</type2>
                <value>0</value>
            </restriction>
            <restriction>
                <type>Re</type>
                <type2>Se</type2>
                <value>0</value>
            </restriction>
        </restrictions>
    </race>
    <race>
        <name>Grauelf</name>
        <namegenerator>Elves</namegenerator>
        <energy>5</energy>
        <skill>8</skill>
        <intelligence>7</intelligence>
        <charisma>9</charisma>
        <lifebonus>10</lifebonus>
        <spellpower>
            <type>6</type>
            <multiplier>4</multiplier>
            <bonus>0</bonus>
        </spellpower>
        <spellbonus>2</spellbonus>
        <spells>
            <spell>
                <name>Elfenhauch</name>
                <type>NAT</type>
                <power>1-2 ZAK/LK</power>
            </spell>
            <spell>
                <name>Graumantel</name>
                <type>NAT</type>
                <power>3 ZAK</power>
            </spell>
            <spell>
                <name>Wahres sehen</name>
                <type>NAT</type>
                <power>5 ZAK</power>
            </spell>
        </spells>
        <special>Nachtsicht</special>
        <age>
            <type>50</type>
            <multiplier>6</multiplier>
            <bonus>50</bonus>
        </age>
        <height>
            <type>20</type>
            <multiplier>1</multiplier>
            <bonus>160</bonus>
        </height>
        <weight>
            <type>20</type>
            <multiplier>1</multiplier>
            <bonus>40</bonus>
        </weight>
        <freelanguagepoints>6</freelanguagepoints>
        <languages>
            <language>
                <name>Alayani</name>
                <value>6</value>
            </language>
        </languages>
        <restrictions>
            <restriction>
                <type>Sp</type>
                <type2>Pr</type2>
                <value>0</value>
            </restriction>
            <restriction>
                <type>Re</type>
                <type2>Se</type2>
                <value>0</value>
            </restriction>
        </restrictions>
    </race>
    <race>
        <name>Dunkelelf</name>
        <namegenerator>Albion</namegenerator>
        <energy>5</energy>
        <skill>8</skill>
        <intelligence>7</intelligence>
        <charisma>9</charisma>
        <lifebonus>10</lifebonus>
        <spellpower>
            <type>6</type>
            <multiplier>2</multiplier>
            <bonus>0</bonus>
        </spellpower>
        <spellbonus>2</spellbonus>
        <spells>
            <spell>
                <name>Kuss der Finsternis</name>
                <type>NAT</type>
                <power>4 ZAK</power>
            </spell>
            <spell>
                <name>Graumantel</name>
                <type>NAT</type>
                <power>3 ZAK</power>
            </spell>
            <spell>
                <name>Wahres sehen</name>
                <type>NAT</type>
                <power>5 ZAK</power>
            </spell>
        </spells>
        <special>Nachtsicht</special>
        <special>Keine Magier-Spezialisierung ab 10.Rang</special>
        <age>
            <type>50</type>
            <multiplier>6</multiplier>
            <bonus>50</bonus>
        </age>
        <height>
            <type>20</type>
            <multiplier>1</multiplier>
            <bonus>160</bonus>
        </height>
        <weight>
            <type>20</type>
            <multiplier>1</multiplier>
            <bonus>40</bonus>
        </weight>
        <freelanguagepoints>6</freelanguagepoints>
        <languages>
            <language>
                <name>Alayani</name>
                <value>6</value>
            </language>
        </languages>
        <restrictions>
            <restriction>
                <type>Sp</type>
                <type2>Pr</type2>
                <value>0</value>
            </restriction>
            <restriction>
                <type>Re</type>
                <type2>Se</type2>
                <value>0</value>
            </restriction>
        </restrictions>
    </race>
    
    <race>
        <name>Halbling</name>
        <namegenerator>Hobbits</namegenerator>
        <energy>4</energy>
        <skill>9</skill>
        <intelligence>7</intelligence>
        <charisma>8</charisma>
        <lifebonus>10</lifebonus>
        <special>Magie Resistenz -4</special>
        <age>
            <type>20</type>
            <multiplier>1</multiplier>
            <bonus>30</bonus>
        </age>
        <height>
            <type>10</type>
            <multiplier>3</multiplier>
            <bonus>80</bonus>
        </height>
        <weight>
            <type>20</type>
            <multiplier>2</multiplier>
            <bonus>20</bonus>
        </weight>
        <freelanguagepoints>3</freelanguagepoints>
        <languages>
            <language>
                <name>Suma</name>
                <value>6</value>
            </language>
        </languages>
    </race>
    <race>
        <name>Kobold</name>
        <namegenerator>Deverry</namegenerator>
        <energy>3</energy>
        <skill>10</skill>
        <intelligence>7</intelligence>
        <charisma>7</charisma>
        <lifebonus>5</lifebonus>
        <spellpower>
            <type>6</type>
            <multiplier>2</multiplier>
            <bonus>3</bonus>
        </spellpower>
        <spells>
            <spell>
                <name>Bombenwitz</name>
                <type>HEX</type>
                <power>7 ZAK</power>
            </spell>
            <spell>
                <name>Holterdipolter</name>
                <type>HEX</type>
                <power>2 ZAK</power>
            </spell>
            <spell>
                <name>Plappermaul</name>
                <type>HEX</type>
                <power>2 ZAK/min</power>
            </spell>
            <spell>
                <name>Pustekuchen</name>
                <type>HEX</type>
                <power>4 ZAK</power>
            </spell>
            <spell>
                <name>TÃ¶lpel</name>
                <type>HEX</type>
                <power>6 ZAK</power>
            </spell>
        </spells>
        <age>
            <type>6</type>
            <multiplier>1</multiplier>
            <bonus>10</bonus>
        </age>
        <height>
            <type>20</type>
            <multiplier>1</multiplier>
            <bonus>80</bonus>
        </height>
        <weight>
            <type>10</type>
            <multiplier>2</multiplier>
            <bonus>10</bonus>
        </weight>
        <freelanguagepoints>3</freelanguagepoints>
        <languages>
            <language>
                <name>Li'Endi</name>
                <value>6</value>
            </language>
        </languages>
        <restrictions>
            <restriction>
                <type>Pr</type>
                <type2>Sp</type2>
                <value>0</value>
            </restriction>
        </restrictions>
    </race>
    <race>
        <name>Riese</name>
        <namegenerator>Greek</namegenerator>
