=== voelkman/Judicator/Judicator/src/java/de/voelkman/config/dtd/weapons.dtd
<?xml version='1.0' encoding="ISO-8859-1"?>
<!ELEMENT assassination
   (assassinationweapon+)
>
<!ELEMENT assassinationweapon
   (name,mk)
>
<!ELEMENT bf
   (#PCDATA)
>
<!ELEMENT bonus
   (#PCDATA)
>
<!ELEMENT df
   (#PCDATA)
>
<!ELEMENT gf
   (#PCDATA)
>
<!ELEMENT melee
   (meleeweapon+)
>
<!ELEMENT meleeweapon
   (name,mk,df,gf,bf,sch,range?)
>

<!ATTLIST meleeweapon
	class (VeryHeavy|Heavy|Light|VeryLight) #REQUIRED
	
>
<!ELEMENT missile
   (missileweapon+)
>
<!ELEMENT missileweapon
   (name,mk,range,sch)
>

<!ELEMENT mk
   (#PCDATA)
>
<!ELEMENT multiplier
   (#PCDATA)
>
<!ELEMENT name
   (#PCDATA)
>
<!ELEMENT range
   (#PCDATA)
>
<!ELEMENT sch
   (multiplier,type,bonus)
>
<!ELEMENT type
   (#PCDATA)
>
<!ELEMENT weapons
   (melee,missile,assassination)
>

=== voelkman/Judicator/Judicator/src/java/de/voelkman/config/weapons.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE weapons SYSTEM "dtd/weapons.dtd">
<weapons>
	<melee>
		<meleeweapon class="VeryHeavy">
			<name>Bastardschwert</name>
			<mk>11</mk>
			<df>1</df>
			<gf>3</gf>
			<bf>37</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>5</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryHeavy">
			<name>Bihänder</name>
			<mk>12</mk>
			<df>2</df>
			<gf>3</gf>
			<bf>35</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>6</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="Heavy">
			<name>Degen</name>
			<mk>6</mk>
			<df>2</df>
			<gf>1</gf>
			<bf>25</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>3</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryLight">
			<name>Dolch</name>
			<mk>3</mk>
			<df>3</df>
			<gf>0</gf>
			<bf>18</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>1</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="Heavy">
			<name>Dreizack</name>
			<mk>9</mk>
			<df>3</df>
			<gf>4</gf>
			<bf>13</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>4</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryHeavy">
			<name>Drachenzähne</name>
			<mk>11</mk>
			<df>1</df>
			<gf>4</gf>
			<bf>35</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>6</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryHeavy">
			<name>Hammer</name>
			<mk>10</mk>
			<df>2</df>
			<gf>3</gf>
			<bf>32</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>3</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="Heavy">
			<name>Hellebarde</name>
			<mk>10</mk>
			<df>2</df>
			<gf>4</gf>
			<bf>32</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>3</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryHeavy">
			<name>Höllensterne</name>
			<mk>13</mk>
			<df>4</df>
			<gf>5</gf>
			<bf>28</bf>
			<sch>
				<multiplier>3</multiplier>
				<type>6</type>
				<bonus>0</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryHeavy">
			<name>Kampfaxt</name>
			<mk>10</mk>
			<df>2</df>
			<gf>3</gf>
			<bf>29</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>4</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="Heavy">
			<name>Kampfstab</name>
			<mk>6</mk>
			<df>0</df>
			<gf>2</gf>
			<bf>19</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>2</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryHeavy">
			<name>Keule</name>
			<mk>6</mk>
			<df>2</df>
			<gf>1</gf>
			<bf>17</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>2</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="Heavy">
			<name>Kurzschwert</name>
			<mk>7</mk>
			<df>1</df>
			<gf>2</gf>
			<bf>39</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>2</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryHeavy">
			<name>Lanze</name>
			<mk>12</mk>
			<df>10</df>
			<gf>0</gf>
			<bf>15</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>5</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryLight">
			<name>Messer</name>
			<mk>2</mk>
			<df>4</df>
			<gf>0</gf>
			<bf>12</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>0</bonus>
			</sch>
			<range>15</range>
		</meleeweapon>
		<meleeweapon class="VeryHeavy">
			<name>Morgenstern</name>
			<mk>11</mk>
			<df>3</df>
			<gf>4</gf>
			<bf>31</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>5</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="Light">
			<name>Peitsche</name>
			<mk>4</mk>
			<df>6</df>
			<gf>1</gf>
			<bf>23</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>2</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="Light">
			<name>Rapier</name>
			<mk>6</mk>
			<df>2</df>
			<gf>1</gf>
			<bf>22</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>3</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="Heavy">
			<name>Säbel</name>
			<mk>8</mk>
			<df>1</df>
			<gf>2</gf>
			<bf>28</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>3</bonus>
			</sch>
		</meleeweapon>
			<meleeweapon class="Heavy">
			<name>Katana</name>
			<mk>10</mk>
			<df>1</df>
			<gf>0</gf>
			<bf>32</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>4</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryHeavy">
			<name>Schwert</name>
			<mk>9</mk>
			<df>0</df>
			<gf>3</gf>
			<bf>40</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>4</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="Heavy">
			<name>Sense</name>
			<mk>10</mk>
			<df>2</df>
			<gf>4</gf>
			<bf>11</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>3</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryLight">
			<name>Sichel</name>
			<mk>3</mk>
			<df>4</df>
			<gf>1</gf>
			<bf>18</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>1</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryHeavy">
			<name>Speer</name>
			<mk>9</mk>
			<df>2</df>
			<gf>4</gf>
			<bf>11</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>3</bonus>
			</sch>
			<range>30</range>
		</meleeweapon>
		<meleeweapon class="VeryHeavy">
			<name>Wurfaxt</name>
			<mk>11</mk>
			<df>4</df>
			<gf>4</gf>
			<bf>20</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>3</bonus>
			</sch>
			<range>15</range>
		</meleeweapon>
		<meleeweapon class="VeryHeavy">
			<name>Streitkolben</name>
			<mk>8</mk>
			<df>1</df>
			<gf>3</gf>
			<bf>30</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>3</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryLight">
			<name>Teufelshörner</name>
			<mk>4</mk>
			<df>3</df>
			<gf>1</gf>
			<bf>14</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>2</bonus>
			</sch>
		</meleeweapon>
		<meleeweapon class="VeryHeavy">
			<name>Trihänder</name>
			<mk>15</mk>
			<df>2</df>
			<gf>5</gf>
			<bf>32</bf>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>8</bonus>
			</sch>
		</meleeweapon>
	</melee>
	<missile>
		<missileweapon>
			<name>Armbrust</name>
			<mk>12</mk>
			<range>80</range>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>5</bonus>
			</sch>
		</missileweapon>
		<missileweapon>
			<name>Armbrust (leicht)</name>
			<mk>10</mk>
			<range>60</range>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>3</bonus>
			</sch>
		</missileweapon>
		<missileweapon>
			<name>Blasrohr</name>
			<mk>1</mk>
			<range>15</range>
			<sch>
				<multiplier>1</multiplier>
				<type>3</type>
				<bonus>0</bonus>
			</sch>
		</missileweapon>
		<missileweapon>
			<name>Bola</name>
			<mk>6</mk>
			<range>15</range>
			<sch>
				<multiplier>1</multiplier>
				<type>3</type>
				<bonus>0</bonus>
			</sch>
		</missileweapon>
		<missileweapon>
			<name>Bumerang</name>
			<mk>7</mk>
			<range>30</range>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>1</bonus>
			</sch>
		</missileweapon>
		<missileweapon>
			<name>Handbrust</name>
			<mk>4</mk>
			<range>15</range>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>2</bonus>
			</sch>
		</missileweapon>
			<missileweapon>
			<name>Feuerbüchse</name>
			<mk>9</mk>
			<range>80</range>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>4</bonus>
			</sch>
		</missileweapon>
		<missileweapon>
			<name>Kurzbogen</name>
			<mk>8</mk>
			<range>50</range>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>3</bonus>
			</sch>
		</missileweapon>
		<missileweapon>
			<name>Langbogen</name>
			<mk>11</mk>
			<range>80</range>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>4</bonus>
			</sch>
		</missileweapon>
		<missileweapon>
			<name>Langrohr</name>
			<mk>1</mk>
			<range>30</range>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>0</bonus>
			</sch>
		</missileweapon>
		<missileweapon>
			<name>Schleuder</name>
			<mk>7</mk>
			<range>30</range>
			<sch>
				<multiplier>1</multiplier>
				<type>6</type>
				<bonus>1</bonus>
			</sch>
		</missileweapon>
		<missileweapon>
			<name>Shuirken</name>
			<mk>4</mk>
			<range>15</range>
			<sch>
				<multiplier>1</multiplier>
				<type>3</type>
				<bonus>1</bonus>
			</sch>
		</missileweapon>
		<missileweapon>
			<name>Zwylle</name>
			<mk>1</mk>
			<range>15</range>
			<sch>
				<multiplier>1</multiplier>
				<type>3</type>
				<bonus>0</bonus>
			</sch>
		</missileweapon>
	</missile>
	<assassination>
		<assassinationweapon>
			<name>Garotte</name>
			<mk>2</mk>
		</assassinationweapon>
		<assassinationweapon>
			<name>Totschläger</name>
			<mk>3</mk>
		</assassinationweapon>
	</assassination>
</weapons>
